name: Build and deploy Node.js app to Azure Web App - gradebook

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Set DATABASE_URL environment variable
        run: echo "DATABASE_URL=${{ secrets.AZURE_DATABASE_URL }}" > ./backend_gradebook/.env

      - name: Debug DATABASE_URL
        run: cat ./backend_gradebook/.env

      - name: Install dependencies and fix permissions
        working-directory: ./backend_gradebook
        run: |
          npm install --unsafe-perm
          chmod +x ./node_modules/.bin/prisma

      - name: Run Prisma migrations
        working-directory: ./backend_gradebook
        run: npx prisma migrate deploy

      - name: Run tests
        working-directory: ./backend_gradebook
        env:
          TERM: xterm
        run: npm run test

      - name: Zip artifact for deployment
        working-directory: ./backend_gradebook
        run: zip ../release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B5757047B5D7475E86CD8CC71A74072F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_94D252A275014E249A1FC64010EC7371 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CA9F716C92324C88A70652E5E64D600A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'gradebook'
          slot-name: 'Production'
          package: .
